# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cliente_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tabela(object):
    def setupUi(self, Tabela):
        Tabela.setObjectName("Tabela")
        Tabela.resize(582, 475)
        self.tabela = QtWidgets.QTableWidget(Tabela)
        self.tabela.setGeometry(QtCore.QRect(60, 90, 461, 321))
        self.tabela.setObjectName("tabela")
        self.tabela.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(2, item)
        self.label = QtWidgets.QLabel(Tabela)
        self.label.setGeometry(QtCore.QRect(60, 30, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Tabela)
        QtCore.QMetaObject.connectSlotsByName(Tabela)

    def retranslateUi(self, Tabela):
        _translate = QtCore.QCoreApplication.translate
        Tabela.setWindowTitle(_translate("Tabela", "Form"))
        item = self.tabela.horizontalHeaderItem(0)
        item.setText(_translate("Tabela", "Nome"))
        item = self.tabela.horizontalHeaderItem(1)
        item.setText(_translate("Tabela", "Email"))
        item = self.tabela.horizontalHeaderItem(2)
        item.setText(_translate("Tabela", "Telefone"))
        __sortingEnabled = self.tabela.isSortingEnabled()

        self.tabela.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Tabela", "Clientes Cadastrados"))

    def mostrarClientes(self, dados):
        _translate = QtCore.QCoreApplication.translate
        self.tabela.setRowCount(len(dados))

        for i in range(len(dados)):
            for j in range(1, 4):
                item = QtWidgets.QTableWidgetItem(_translate("Tabela", dados[i][j]))
                self.tabela.setItem(i, j-1, item)




